### ISSUE TITLE
can't find pyqt4-dev-tools

### ISSUE THREAD

**Issue by wanghui589** [cgvict/roLabelImg#29]
the ubuntu system 
can't find pyqt4-dev-tools
can anyone help me

**Comment by antoinekeller** [comment]
I had the same issue on Ubuntu 22.04

You can run:
```
sudo apt-get install pyqt5-dev-tools
make qt5py3
python3 roLabelImg.py
```

Hope it helps

**Comment by Ch1cker** [comment]
> I had the same issue on Ubuntu 22.04
> 
> You can run:
> 
> ```
> sudo apt-get install pyqt5-dev-tools
> make qt5py3
> python3 roLabelImg.py
> ```
> 
> Hope it helps

a new bug:
`pyrcc5 -o resources.py resources.qrc
running with lxml.etree
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "roLabelImg.py", line 1441, in <module>
    sys.exit(main(sys.argv))
  File "roLabelImg.py", line 1437, in main
    app, _win = get_main_app(argv)
  File "roLabelImg.py", line 1429, in get_main_app
    win = MainWindow(argv[1] if len(argv) >= 2 else None,
  File "roLabelImg.py", line 472, in __init__
    self.recentFiles = list(settings.get('recentFiles', []))
TypeError: 'NoneType' object is not iterable
`

>

**Comment by karantai** [comment]
@Ch1cker please create a new issue for clarity, if there is not one already.

In order to solve this issue change the line in 472 to this:
`self.recentFiles = list(settings.get('recentFiles') or [])`.

Hope this works
