### ISSUE TITLE
PyQt4”: ValueError: PyCapsule_GetPointer called with incorrect names()

### ISSUE THREAD

**Issue by DIANSLEE** [cgvict/roLabelImg#33]
### issue1

- **OS:** Windows

- **PyQt version:** 4

```
(ro) C:\Users\dians\Desktop\deep\roLabelImg-master>python rolabelimg.py
Traceback (most recent call last):
  File "rolabelimg.py", line 27, in <module>
    import resources
  File "C:\Users\dians\Desktop\deep\roLabelImg-master\resources.py", line 9, in <module>
    from PyQt4 import QtCore
ValueError: PyCapsule_GetPointer called with incorrect names()
```

**Comment by DIANSLEE** [comment]
pyrcc5 -o resources.py resources.qrc(first time pyrcc4, next time is pyrcc5)
