### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by huyi666r** [cgvict/roLabelImg#34]
### issue1

- **OS:**win11

- **Error:** Traceback (most recent call last):
  File "roLabelImg.py", line 1142, in openNextImg
    self.loadFile(filename)
  File "roLabelImg.py", line 933, in loadFile
    self.loadPascalXMLByFilename(xmlPath)
  File "roLabelImg.py", line 1287, in loadPascalXMLByFilename
    tVocParseReader = PascalVocReader(xmlPath)
  File "E:\dt\roLabelImg-master\libs\pascal_voc_io.py", line 207, in __init__
    self.parseXML()
  File "E:\dt\roLabelImg-master\libs\pascal_voc_io.py", line 264, in parseXML
    if typeItem.text == 'bndbox':
AttributeError: 'NoneType' object has no attribute 'text'

```

**Comment by karantai** [comment]
Something has happened with the format of the `.xml` files. Now, there is a new format when labelling, which is slightly different that the previous one (for instance, there is a `type` attribute in the new format), so the code breaks. In order to fix it change the lines depicted in the printscreen:

![Screenshot from 2024-07-23 15-48-20](https://github.com/user-attachments/assets/62a2b651-56f2-493a-b9e1-723d7ef1b451)
