### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Thaumaturge2020** [cgvict/roLabelImg#35]
### issue1

- **OS:** mac os

- **PyQt version:** 5

- **Error:** Segmentation fault: 438

```
running with cElementTree on Python 2.5+
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "./roLabelImg.py", line 1364, in <module>
    sys.exit(main(sys.argv))
  File "./roLabelImg.py", line 1360, in main
    app, _win = get_main_app(argv)
  File "./roLabelImg.py", line 1352, in get_main_app
    win = MainWindow(argv[1] if len(argv) >= 2 else None,
  File "./roLabelImg.py", line 438, in __init__
    self.recentFiles = list(settings.get('recentFiles', []))
TypeError: 'NoneType' object is not iterable
```

**Comment by YDBOCHIS** [comment]
try to modify line 438:
self.recentFiles = list(settings.get('recentFiles') or [])
