### ISSUE TITLE
couldn't open annotation files

### ISSUE THREAD

**Issue by hurricanedjp** [cgvict/roLabelImg#6]
### issue1

- **OS:** ubuntu16.04

- **PyQt version:** 4

- **Error:** ./labelImg.py 
running with lxml.etree
Traceback (most recent call last):
  File "./labelImg.py", line 1156, in openFile
    self.loadFile(filename)
  File "./labelImg.py", line 902, in loadFile
    self.lineColor = QColor(*self.labelFile.lineColor)
AttributeError: 'LabelFile' object has no attribute 'lineColor'

when I run ./labelimg.py,  a error as above occurs...
Also,after I finish labeling the image , I couldn't open annotation files.

**Comment by banderlog** [comment]
The same thing with qt5py3 from `git clone`, and releases `1.7.0` and `1.6.0`.

**Comment by SGQ-py** [comment]
请问您现在解决了吗？
我也遇到了您现在的情况
